[workspace]
members = [
    "druid",
    "druid-shell",
    "druid-derive",
    "widget-cruncher",
    "docs/book_examples",
    "druid/examples/web",
    "druid/examples/hello_web",
    "druid/examples/value_formatting",
]
default-members = [
    "druid",
    "druid-shell",
    "druid-derive",
]

[profile.coverage]
inherits = "test"
